// sync.js — one child, two devices.
//
// THE SHAPE
// The server is a dumb box keyed by a secret code: it stores a save and hands it
// back. All the intelligence is here, and specifically the merge is the one in
// js/progress.js that the tests already cover. Every sync is read → merge →
// write, so it does not matter which device went first, whether one of them was
// offline for a week, or whether the same sync runs twice.
//
// WHAT IT MUST NEVER DO
// Break the game. Sync is best-effort in every direction: no server configured,
// server down, wifi off, wrong code, clock skew — the child still plays, and the
// local save is still the truth. Nothing here is ever awaited on a path the
// child is waiting on.
//
// WHERE THE SECRET LIVES
// In its own localStorage key, deliberately NOT in the save. The save is what
// gets exported and handed to someone to look at, and a sync code inside it
// would be a password in a file the parent thinks is a report.

const SYNC = {
  _key: 'tower_control_sync',
  TIMEOUT_MS: 9000,

  /** { url, code, lastAt, lastError } */
  config() {
    try {
      return Object.assign({ url: '', code: '', lastAt: 0, lastError: '' },
                           JSON.parse(localStorage.getItem(this._key) || '{}'));
    } catch (e) {
      return { url: '', code: '', lastAt: 0, lastError: '' };
    }
  },

  setConfig(patch) {
    const next = Object.assign(this.config(), patch);
    try { localStorage.setItem(this._key, JSON.stringify(next)); } catch (e) { /* ignore */ }
    return next;
  },

  enabled() {
    const c = this.config();
    return !!(c.url && c.code);
  },

  /**
   * A fresh code. 20 chars from a 32-symbol alphabet ≈ 100 bits, generated by
   * the browser's CSPRNG — this is the only thing standing between a stranger
   * and the slot, so it is not Math.random().
   */
  makeCode() {
    const alphabet = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'; // no O/0/I/1 — it gets typed by hand
    const bytes = new Uint8Array(20);
    (window.crypto || window.msCrypto).getRandomValues(bytes);
    return [...bytes].map(b => alphabet[b % alphabet.length]).join('');
  },

  /** Same validation as the server, applied before we bother it. */
  validCode(code) { return /^[A-Za-z0-9_-]{16,64}$/.test(String(code || '')); },

  validUrl(url) {
    try {
      const u = new URL(url);
      // http:// would be blocked by the browser anyway once the game is served
      // over https — better to say so here than to fail mysteriously later.
      return u.protocol === 'https:' || u.hostname === 'localhost' || u.hostname === '127.0.0.1';
    } catch (e) {
      return false;
    }
  },

  _endpoint(cfg) {
    const u = new URL(cfg.url);
    u.searchParams.set('code', cfg.code);
    return u.toString();
  },

  async _fetch(url, opts) {
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), this.TIMEOUT_MS);
    try {
      const res = await fetch(url, Object.assign({ signal: ctrl.signal, cache: 'no-store' }, opts));
      const text = await res.text();
      let body = null;
      try { body = text ? JSON.parse(text) : null; } catch (e) { body = null; }
      if (!res.ok) {
        throw new Error((body && body.error) ? body.error : 'HTTP ' + res.status);
      }
      if (body === null) throw new Error('the server did not answer with JSON');
      return body;
    } finally {
      clearTimeout(timer);
    }
  },

  /** What the server currently holds, or null if the slot is empty. */
  async pull() {
    const cfg = this.config();
    const body = await this._fetch(this._endpoint(cfg), { method: 'GET' });
    return body.save || null;
  },

  /**
   * What the server currently holds, without writing anything.
   *
   * The whole system is otherwise invisible: a parent looking at a device with
   * no history cannot tell whether the server is empty too, or whether he is
   * simply standing at the wrong machine. This answers that in one line.
   */
  async peek() {
    if (!this.enabled()) return { ok: false, reason: 'not-configured' };
    try {
      const cfg = this.config();
      const body = await this._fetch(this._endpoint(cfg), { method: 'GET' });
      return { ok: true, save: body.save || null, updatedAt: body.updatedAt || null };
    } catch (err) {
      return { ok: false, reason: err.name === 'AbortError' ? 'timeout' : (err.message || 'failed') };
    }
  },

  /** A one-line description of a save, for comparing two sides at a glance. */
  describe(save) {
    if (!save) return null;
    const parts = [];
    if (save.playerName) parts.push(save.playerName);
    parts.push('נָמֵל ' + (save.currentStage || 1));
    parts.push((save.planesCollected || []).length + ' מְטוֹסִים');
    parts.push((save.log || []).length + ' תַּרְגִּילִים');
    return parts.join(' · ');
  },

  async push(save) {
    const cfg = this.config();
    return this._fetch(this._endpoint(cfg), {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(save),
    });
  },

  /**
   * Read, merge, write. Returns the save that should now be in localStorage.
   *
   * Always writes back, even when the remote had nothing new: the other device
   * may be the one that is behind, and it is the write that fixes that.
   */
  async sync(localSave) {
    if (!this.enabled()) return { ok: false, reason: 'not-configured', save: localSave };

    try {
      const remote = await this.pull();
      const merged = remote ? PROGRESS.merge(localSave, remote) : localSave;
      await this.push(merged);
      this.setConfig({ lastAt: Date.now(), lastError: '' });
      return {
        ok: true,
        save: merged,
        pulled: remote ? (remote.log || []).length : 0,
        gained: (merged.log || []).length - (localSave.log || []).length,
      };
    } catch (err) {
      // Offline, asleep, mistyped — all the same to the child, who is unaffected.
      const reason = err.name === 'AbortError' ? 'timeout' : (err.message || 'failed');
      this.setConfig({ lastError: reason });
      return { ok: false, reason, save: localSave };
    }
  },

  /** Fire-and-forget: never blocks, never throws, never interrupts a shift. */
  syncInBackground(localSave, onDone) {
    if (!this.enabled()) return;
    this.sync(localSave).then(res => {
      if (res.ok && res.gained > 0) PROGRESS.save(res.save);
      if (onDone) { try { onDone(res); } catch (e) { /* never the caller's problem */ } }
    }).catch(() => { /* already handled inside sync() */ });
  },
};

if (typeof module !== 'undefined' && module.exports) module.exports = SYNC;
